
const ROW_1 = [
    { name: 'AA' },
    { name: 'AKs' },
    { name: 'AQs' },
    { name: 'AJs' },
    { name: 'ATs' },
    { name: 'A9s' },
    { name: 'A8s' },
    { name: 'A7s' },
    { name: 'A6s' },
    { name: 'A5s' },
    { name: 'A4s' },
    { name: 'A3s' },
    { name: 'A2s' },
]
const ROW_2 = [
    { name: 'AKo' },
    { name: 'KK' },
    { name: 'KQs' },
    { name: 'KJs' },
    { name: 'KTs' },
    { name: 'K9s' },
    { name: 'K8s' },
    { name: 'K7s' },
    { name: 'K6s' },
    { name: 'K5s' },
    { name: 'K4s' },
    { name: 'K3s' },
    { name: 'K2s' },
]
const ROW_3 = [
    { name: 'AQo' },
    { name: 'KQ' },
    { name: 'QQ' },
    { name: 'QJs' },
    { name: 'QTs' },
    { name: 'Q9s' },
    { name: 'Q8s' },
    { name: 'Q7s' },
    { name: 'Q6s' },
    { name: 'Q5s' },
    { name: 'Q4s' },
    { name: 'Q3s' },
    { name: 'Q2s' },
]
const ROW_4 = [
    { name: 'AJo' },
    { name: 'KJo' },
    { name: 'QJo' },
    { name: 'JJ' },
    { name: 'JTs' },
    { name: 'J9s' },
    { name: 'J8s' },
    { name: 'J7s' },
    { name: 'J6s' },
    { name: 'J5s' },
    { name: 'J4s' },
    { name: 'J3s' },
    { name: 'J2s' },
]
const ROW_5 = [
    { name: 'ATo' },
    { name: 'KTo' },
    { name: 'QTo' },
    { name: 'JTo' },
    { name: 'TT' },
    { name: 'T9s' },
    { name: 'T8s' },
    { name: 'T7s' },
    { name: 'T6s' },
    { name: 'T5s' },
    { name: 'T4s' },
    { name: 'T3s' },
    { name: 'T2s' },
]
const ROW_6 = [
    { name: 'A9o' },
    { name: 'K9o' },
    { name: 'Q9o' },
    { name: 'J9o' },
    { name: 'T9o' },
    { name: '99' },
    { name: '98s' },
    { name: '97s' },
    { name: '96s' },
    { name: '95s' },
    { name: '94s' },
    { name: '93s' },
    { name: '92s' },
]
const ROW_7 = [
    { name: 'A8o' },
    { name: 'K8o' },
    { name: 'Q8o' },
    { name: 'J8o' },
    { name: 'T8o' },
    { name: '98o' },
    { name: '88' },
    { name: '87s' },
    { name: '86s' },
    { name: '85s' },
    { name: '84s' },
    { name: '83s' },
    { name: '82s' },
]
const ROW_8 = [
    { name: 'A7o' },
    { name: 'K7o' },
    { name: 'Q7o' },
    { name: 'J7o' },
    { name: 'T7o' },
    { name: '97o' },
    { name: '87o' },
    { name: '77' },
    { name: '76s' },
    { name: '75s' },
    { name: '74s' },
    { name: '73s' },
    { name: '72s' },
]
const ROW_9 = [
    { name: 'A6o' },
    { name: 'K6o' },
    { name: 'Q6o' },
    { name: 'J6o' },
    { name: 'T6o' },
    { name: '96o' },
    { name: '86o' },
    { name: '76o' },
    { name: '66' },
    { name: '65s' },
    { name: '64s' },
    { name: '63s' },
    { name: '62s' },
]
const ROW_10 = [
    { name: 'A5o' },
    { name: 'K5o' },
    { name: 'Q5o' },
    { name: 'J5o' },
    { name: 'T5o' },
    { name: '95o' },
    { name: '85o' },
    { name: '75o' },
    { name: '65o' },
    { name: '55' },
    { name: '54s' },
    { name: '53s' },
    { name: '52s' },
]
const ROW_11 = [
    { name: 'A4o' },
    { name: 'K4o' },
    { name: 'Q4o' },
    { name: 'J4o' },
    { name: 'T4o' },
    { name: '94o' },
    { name: '84o' },
    { name: '74o' },
    { name: '64o' },
    { name: '54o' },
    { name: '44' },
    { name: '43s' },
    { name: '42s' },
]
const ROW_12 = [
    { name: 'A3o' },
    { name: 'K3o' },
    { name: 'Q3o' },
    { name: 'J3o' },
    { name: 'T3o' },
    { name: '93o' },
    { name: '83o' },
    { name: '73o' },
    { name: '63o' },
    { name: '53o' },
    { name: '43o' },
    { name: '33' },
    { name: '32s' },
]
const ROW_13 = [
    { name: 'A2o' },
    { name: 'K2o' },
    { name: 'Q2o' },
    { name: 'J2o' },
    { name: 'T2o' },
    { name: '92o' },
    { name: '82o' },
    { name: '72o' },
    { name: '62o' },
    { name: '52o' },
    { name: '42o' },
    { name: '32o' },
    { name: '22' },
]

const CARDS = [
    ...ROW_1,
    ...ROW_2,
    ...ROW_3,
    ...ROW_4,
    ...ROW_5,
    ...ROW_6,
    ...ROW_7,
    ...ROW_8,
    ...ROW_9,
    ...ROW_10,
    ...ROW_11,
    ...ROW_12,
    ...ROW_13,
]

export { CARDS }